### ISSUE TITLE
please fix for csgo servers :(

### ISSUE THREAD

**Issue by Drmohammad11** [JoinedSenses/TF2-ServerHop#1]
i have this erorr:

L 01/09/2019 - 06:59:59: SourceMod error session started
L 01/09/2019 - 06:59:59: Info (map "de_dust2") (file "errors_20190109.log")
L 01/09/2019 - 06:59:59: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 01/09/2019 - 06:59:59: [SM] Blaming: Addons_server_hop.smx
L 01/09/2019 - 06:59:59: [SM] Call stack trace:
L 01/09/2019 - 06:59:59: [SM]   [1] Line 102, Addons_server_hop.sp::OnPluginStart
L 01/09/2019 - 06:59:59: [SM] Unable to load plugin "Addons_server_hop.smx": Error detected in plugin startup (see error logs)
L 01/09/2019 - 07:07:37: SourceMod error session started
L 01/09/2019 - 07:07:37: Info (map "de_mirage") (file "errors_20190109.log")
L 01/09/2019 - 07:07:37: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 01/09/2019 - 07:07:38: [SM] Blaming: Addons_server_hop.smx
L 01/09/2019 - 07:07:38: [SM] Call stack trace:
L 01/09/2019 - 07:07:38: [SM]   [1] Line 102, Addons_server_hop.sp::OnPluginStart
L 01/09/2019 - 07:07:38: [SM] Unable to load plugin "Addons_server_hop.smx": Error detected in plugin startup (see error logs)

**Comment by JoinedSenses** [comment]
How many servers are you adding? If it's more than 10, then you need to increase MAX_SERVERS and recompile. This isn't a plugin bug.
