### ISSUE TITLE
[csgo] i can not join the server on the game!!

### ISSUE THREAD

**Issue by Drmohammad11** [JoinedSenses/TF2-ServerHop#2]
hi,
i use !servers but i can not join to the servers on the list hop!!!
how i can fixed this problem??

**Comment by JoinedSenses** [comment]
This plugin version probably doesn't for CS:GO - I haven't tested it, only for TF2. It uses a command `redirect`, which I don't think exists in that game.

https://forums.alliedmods.net/showpost.php?p=1917889&postcount=352

**Comment by JoinedSenses** [comment]
https://forums.alliedmods.net/showpost.php?p=1849548&postcount=317
