### ISSUE TITLE
[TF2] Plugin won't start <Bad Load>

### ISSUE THREAD

**Issue by Alex-Thunderhunter** [JoinedSenses/TF2-ServerHop#4]
When listing the plugins list through the console, it shows <Bad Load> serverhop.smx and at the bottom of the list it shows serverhop.smx: Unable to load plugin (no debug string table). Is there a way to fix this, Serverhop is the only server switching plugin that has advertisements for the server list.

**Comment by Alex-Thunderhunter** [comment]
Version 8.2 works, I'd still look into it though

**Comment by Alex-Thunderhunter** [comment]
The older versions of the plugin require a user to press F3 to accept the connection. This no longer works. But in the current version it uses redirect but can't be loaded.

**Comment by JoinedSenses** [comment]
Recompile with SM 1.9 or upgrade to SM 1.10.

`(no debug string table)` indicates a version conflict.

If you have issues, contact me on discord JoinedSenses#0001
