### ISSUE TITLE
Which compiler to use ? (Suggested compiler 1.2.4 on alliedmodders doesn't compile at all)

### ISSUE THREAD

**Issue by RSA-encryption** [JoinedSenses/TF2-ServerHop#6]
I've been wondering which compiler to use since 1.2.4 and 1.10 throw way too many errors so I'm just going to ask to save two hours googling solutions. Which compiler am I supposed to use ? If you'd be so kind please add the compiler to the repo or add info to the readme.

Thanks.

**Comment by JoinedSenses** [comment]
1.2.4? why would you have a 1.2.4 spcomp version? Post the compiler errors you are receiving. This works with 1.10+. Make sure you have the socket include that is required: https://github.com/JoinedSenses/sm-ext-socket/blob/master/scripting/include/socket.inc

**Comment by JoinedSenses** [comment]
The plugin is already built at https://github.com/JoinedSenses/TF2-ServerHop/tree/master/plugins

**Comment by RSA-encryption** [comment]
Thanks for the info. Also the thing is that someone recommended recompiling it with 1.2.4 on alliedmodders hence why I tried to use 1.2.4. Will try to compile it with 1.10 again. Also I need to modify the source which is why I'm not using the built version.

Again thanks for quick reply !

**Comment by JoinedSenses** [comment]
1.2.4 was released 11 years ago - it's quite outdated.
