### ISSUE TITLE
Invalid memory access.

### ISSUE THREAD

**Issue by Chdata** [JoinedSenses/TF2-ServerHop#9]
``L 08/19/2022 - 02:57:06: [SM] Call stack trace:
L 08/19/2022 - 02:57:06: [SM]   [1] Line 232, C:\Users\scripting\serverhop.sp::GetByte
L 08/19/2022 - 02:57:06: [SM]   [2] Line 269, C:\Users\scripting\serverhop.sp::OnSocketReceive
L 08/19/2022 - 02:58:06: [SM] Exception reported: Invalid memory access
L 08/19/2022 - 02:58:06: [SM] Blaming: serverhop.smx``

I'm getting rapid error spam. It does go away after the servers seem to connect properly, but it easily fills a huge errorlog file beforehand.

**Comment by JoinedSenses** [comment]
Are you using latest version? Those lines don't match up with what's on the repo.

**Comment by Chdata** [comment]
Seems I merely had an outdated .smx running!
